### PR TITLE
fix(#799): batch contact IDs in move-contacts to avoid URI length errors

### LINKED ISSUE #799: Getting "414 Request-URI Too Large" when moving contacts on CHT 5.x
**Describe the bug**
The `move-contacts` action fails with a `414 Request-URI Too Large` error when the contact being moved has a large number of descendants. 

**To Reproduce**

1. Have a CHT instance running cht-core >= 5.0.0 (Nouveau search path)
2. Identify a contact with a large number of descendants (e.g. a health center with over 110 contacts under it)
3. Run: `cht --instance=<instance> move-contacts -- --contacts=<contact_id> --parent=<new_parent_id>`
4. Observe the `414 Request-URI Too Large error` during the "Processing 0 to 10000 report docs" step

**Expected behavior**
The `move-contacts` action should complete successfully regardless of how many descendants the contact has. The descendant IDs should be batched into multiple smaller requests to avoid exceeding URL length limits.

**Logs**
```
> cht --instance=***  --user=medic move-contacts "--" --contacts=1f138ea9-8a37-4067-937e-0ed05a32dd7c --parent=12a8b7ac-9d48-4390-8350-74fcd5c7d169
WARN Project has no dependency on cht-conf.
:key:  Password: *************************
INFO Checking that https://medic:****@***/medic/ is available...
WARN Attempting to use project for medic against non-matching instance: https://medic:****@***
Are you sure? [y/n]: y
INFO Processing config in medic.
INFO Actions:
     - move-contacts
INFO Starting action: move-contacts…
INFO Processing 0 to 10000 report docs
INFO StatusCodeError: 414 - "<html>\r\n<head><title>414 Request-URI Too Large</title></head>\r\n<body>\r\n<center><h1>414 Request-URI Too Large</h1></center>\r\n</body>\r\n</html>\r\n"
    at new StatusCodeError (C:\Users\binok\AppData\Roaming\nvm\v22.21.1\node_modules\cht-conf\node_modules\request-promise-core\lib\errors.js:32:15)
    at plumbing.callback (C:\Users\binok\AppData\Roaming\nvm\v22.21.1\node_modules\cht-conf\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Users\binok\AppData\Roaming\nvm\v22.21.1\node_modules\cht-conf\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\Users\binok\AppData\Roaming\nvm\v22.21.1\node_modules\cht-conf\node_modules\request\request.js:185:22)
    at Request.emit (node:events:519:28)
    at Request.<anonymous> (C:\Users\binok\AppData\Roaming\nvm\v22.21.1\node_modules\cht-conf\node_modules\request\request.js:1154:10)
    at Request.emit (node:events:519:28)
    at IncomingMessage.<anonymous> (C:\Users\binok\AppData\Roaming\nvm\v22.21.1\node_modules\cht-conf\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (node:events:633:28)
    at IncomingMessage.emit (node:events:531:35)

```

**Screenshots**
N/A

**Environment**
- Client platform: Windows
- cht-conf version: 6.0.2
- cht-core version: 5.1.0

**Additional context**
I've never seen this error in earlier version of CHT core (4.x or earlier).

I see that some changes were recently made [here](https://github.com/medic/cht-conf/blob/5f65668e51af4077bee47a1d048b57e313f6d858/src/lib/hierarchy-operations/hierarchy-data-source.js#L78-L81) specifically for CHT core version >= 5.0.0:
https://github.com/medic/cht-conf/blob/5f65668e51af4077bee47a1d048b57e313f6d858/src/lib/hierarchy-operations/hierarchy-data-source.js#L78-L81

We might need a batch size smaller than [10000](https://github.com/medic/cht-conf/blob/5f65668e51af4077bee47a1d048b57e313f6d858/src/lib/hierarchy-operations/hierarchy-data-source.js#L7)?

Also noticed that, when the number of contacts to move is >= 110 but not too large, it throws 400 instead of 414.

### PR DESCRIPTION
**Pull request by binokaryg**
# Description

Split IDs into batches of 100 per request

medic/cht-conf#799

# Code review items

- Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- Tested: Unit and/or integration tests where appropriate
- Backwards compatible: Works with existing data and configuration. Any breaking changes documented in the release notes.

# AI disclosure

This PR was developed with assistance from Claude Code. AI was used for:
- Investigating the root cause of the 414/400/431 errors
- Calculating the URL length threshold (~112 contact IDs for an 8KB limit)
- Implementing the batching fix in `fetchReportsByCreator`

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

File: src/lib/hierarchy-operations/hierarchy-data-source.js [hunk 1]
```diff
@@ -71,18 +72,28 @@ const getFromDbView = async (db, view, keys, skip) => {
   return res.rows.map(row => row.doc);
 };
 
+const fetchReportsBatch = async (db, idsBatch, useNouveau, skip) => {
```
Comment (sugat009) [inline src/lib/hierarchy-operations/hierarchy-data-source.js]: **issue (bug):** The `skip` parameter from the outer pagination loop in `updateReports` (`index.js:78-92`) is passed identically to every sub-batch here. This means on iteration 2 of the outer loop (`skip=10000`), each of the sub-batch queries independently skips 10,000 rows from its own small result set, likely returning 0 results. The outer loop then terminates early, silently missing reports.

The inner ID-batching loop and the outer report-pagination loop serve different purposes. The inner loop should always fetch all reports for its ID batch. The outer `skip` should not leak into it.

Also, `allResults` accumulates across all sub-batches, so the total can exceed `BATCH_SIZE`, which breaks the outer loop's termination condition (`reportDocsBatch.length >= BATCH_SIZE`).

File: src/lib/hierarchy-operations/hierarchy-data-source.js [hunk 2]
```diff
@@ -71,18 +72,28 @@ const getFromDbView = async (db, view, keys, skip) => {
...
+  if (useNouveau) {
+    return api().getReportsByCreatedByIds(idsBatch, BATCH_SIZE, skip);
```
Comment (sugat009) [inline src/lib/hierarchy-operations/hierarchy-data-source.js]: **suggestion (improvement):** The Nouveau endpoint uses POST with the query in the request body (see `cht-core/shared-libs/cht-datasource/src/local/libs/nouveau.ts`), so there is no URI length constraint on this path. The URI-too-large issue from #799 only affects the CouchDB view path (CHT < 5.0.0).

Nouveau also uses bookmark-based pagination rather than `skip`, so the batching of contact IDs is unnecessary here. Consider only applying the ID batching to the CouchDB view branch.

File: src/lib/hierarchy-operations/hierarchy-data-source.js [hunk 3]
```diff
@@ -71,18 +72,28 @@ const getFromDbView = async (db, view, keys, skip) => {
...
+  for (let i = 0; i < createdByIds.length; i += QUERY_IDS_BATCH_SIZE) {
+    const idsBatch = createdByIds.slice(i, i + QUERY_IDS_BATCH_SIZE);
+    const batchResults = await fetchReportsBatch(db, idsBatch, useNouveau, skip);
+    allResults.push(...batchResults);
   }
-
-  const createdByKeys = createdByIds.map(id => [`contact:${id}`]);
-  return await getFromDbView(db, 'medic-client/reports_by_freetext', createdByKeys, skip);
+  return allResults;
 };
```
Comment (sugat009) [inline src/lib/hierarchy-operations/hierarchy-data-source.js:93]: **question (consistency):** `fetchReportsBySubject` (just below) passes all IDs directly to `getFromDbView` without batching. If the contact has many subject IDs, this has the same URI length vulnerability that this PR is fixing. Should this be batched as well for consistency?

**Review by sugat009 — CHANGES_REQUESTED** [review]
The ID batching approach is sound for avoiding the URI length issue, but there are a few concerns with the current implementation.

File: src/lib/hierarchy-operations/hierarchy-data-source.js (hunk 1 above)
Comment (binokaryg) [reply src/lib/hierarchy-operations/hierarchy-data-source.js]: Thanks, I have removed `skip` from internal functions and applied it here:
https://github.com/medic/cht-conf/blob/88bf4a80315f545770ce9f0ec5ad4c50771e8dab/src/lib/hierarchy-operations/hierarchy-data-source.js#L105

File: src/lib/hierarchy-operations/hierarchy-data-source.js (hunk 2 above)
Comment (binokaryg) [reply src/lib/hierarchy-operations/hierarchy-data-source.js]: Thanks, `api.js` is now updated  to use `request.post` with body instead of `request.get`.

File: src/lib/hierarchy-operations/hierarchy-data-source.js (hunk 3 above)
Comment (binokaryg) [reply src/lib/hierarchy-operations/hierarchy-data-source.js:93]: Here's an advice I got from Claude:
> It is not a concern. `createdAtIds` comes from `getReportsCreatedAtId`s which returns at most 2 IDs (the `sourceId` and optionally `sourcePrimaryContactId`), and only during merge operations. It will never be large enough to cause a URI issue. PouchDB also sends keys via POST body anyway.

https://github.com/medic/cht-conf/blob/88bf4a80315f545770ce9f0ec5ad4c50771e8dab/src/lib/hierarchy-operations/index.js#L97-L108

File: src/lib/hierarchy-operations/hierarchy-data-source.js [hunk 4]
```diff
@@ -71,37 +71,38 @@ const getFromDbView = async (db, view, keys, skip) => {
...
 
   const coreVersion = await getValidApiVersion();
   if (coreVersion && semver.gte(coreVersion, NOUVEAU_MIN_VERSION)) {
-    return await api().getReportsByCreatedByIds(createdByIds, BATCH_SIZE, skip);
+    return await api().getReportsByCreatedByIds(createdByIds, BATCH_SIZE, 0);
   }
 
   const createdByKeys = createdByIds.map(id => [`contact:${id}`]);
-  return await getFromDbView(db, 'medic-client/reports_by_freetext', createdByKeys, skip);
+  return await getFromDbView(db, 'medic-client/reports_by_freetext', createdByKeys, 0);
```
Comment (sugat009) [inline src/lib/hierarchy-operations/hierarchy-data-source.js]: **question:** Both inner functions (`fetchReportsByCreator` and `fetchReportsBySubject`) always fetch with `skip=0` and `limit=BATCH_SIZE` (10,000), then `getReportsForContacts` combines and slices the result. But the outer loop in `updateReports` calls this repeatedly with increasing `skip`, and each call re-fetches the same capped 10,000 from each source.

If either source has more than 10,000 reports, the inner function can never return beyond the first 10,000, so those extra reports would be permanently missed by the outer loop. Is this a realistic scenario for move/merge operations?

**Review by sugat009 — COMMENTED** [review]
The GET to POST change for Nouveau and the skip fix look good. One question on the updated approach.

File: src/lib/hierarchy-operations/hierarchy-data-source.js (hunk 4 above)
Comment (binokaryg) [reply src/lib/hierarchy-operations/hierarchy-data-source.js]: We definitely need to support moving more than 10,000 reports.
I have had to move contacts with almost 500K reports in the past which took several hours just for the move command to get through.

What do you suggest here?

Comment (sugat009) [reply src/lib/hierarchy-operations/hierarchy-data-source.js]: The simplest and most memory-efficient approach would be to process each report source independently in `updateReports` with its own pagination loop, instead of combining them in `getReportsForContacts`:

```js
async function updateReports(db, options, moveContext) {
  const descendantIds = moveContext.descendantsAndSelf.map(contact => contact._id);
  const createdAtIds = getReportsCreatedAtIds(moveContext);

  let totalCount = 0;

  // Process creator reports with own pagination
  let skip = 0;
  let batch;
  do {
    batch = await fetchReportsByCreator(db, descendantIds, skip);
    processAndWriteBatch(batch, options, moveContext);
    skip += batch.length;
    totalCount += batch.length;
  } while (batch.length >= BATCH_SIZE);

  // Process subject reports with own pagination
  skip = 0;
  do {
    batch = await fetchReportsBySubject(db, createdAtIds, skip);
    processAndWriteBatch(batch, options, moveContext);
    skip += batch.length;
    totalCount += batch.length;
  } while (batch.length >= BATCH_SIZE);

  return totalCount;
}
```

Why this is the most optimal approach:

1. **Memory-efficient**: Only 10K reports in memory at any time. The current approach where both inner functions always fetch with `skip=0` and `limit=BATCH_SIZE`, then the results are combined and sliced, means that if either source has more than 10K reports, the inner function can never return beyond the first 10K. Those extra reports are permanently invisible to the outer loop. With independent pagination, each source pages through all of its own reports correctly.

2. **Each source paginates correctly**: Each source has its own skip counter that increments based only on its own results. No shared skip, no confusion between the two sources.

3. **No combining/dedup complexity needed**: The current dedup via `Map` exists because the two sources can return the same report during merge operations (`createdAtIds` includes `sourceId` and `sourcePrimaryContactId`, which are also in `descendantIds`). With independent loops, if a report appears in both sources, `writeDoc` writes to `{doc._id}.doc.json`, so the second write just overwrites the same file with the same content. Functionally harmless.

4. **`fetchReportsBySubject` is tiny**: It only runs during merge operations and receives at most 2 IDs (`sourceId` and optionally `sourcePrimaryContactId`). It returns a small number of reports and does not really need pagination. The 500K scenario is entirely on the `fetchReportsByCreator` side.

This would remove `getReportsForContacts` entirely and keep the pagination logic straightforward in one place (`updateReports`).

Comment (binokaryg) [reply src/lib/hierarchy-operations/hierarchy-data-source.js]: Thank you for the elaborate feedback @sugat009.
I have applied the changes accordingly.

File: src/lib/api.js [hunk 5]
```diff
@@ -256,13 +256,13 @@ const api = {
     }
   },
 
-  async getReportsByCreatedByIds (createdByIds, limit, skip) {
+  async getReportsByFreetext (createdByIds, limit, skip) {
     const queryString = createdByIds.map(id => `exact_match:"contact:${id}"`).join(' OR ');
-    const res = await request.get(`${environment.apiUrl}/_design/medic/_nouveau/reports_by_freetext`, {
-      qs: {
+    const res = await request.post(`${environment.apiUrl}/_design/medic/_nouveau/reports_by_freetext`, {
+      body: {
```
Comment (sugat009) [inline src/lib/api.js]: **issue (blocking):** Nouveau does not support the `skip` parameter (line 269) — it silently ignores it, causing an infinite loop when results exceed `BATCH_SIZE`.

**Verified from CouchDB source** ([nouveau_httpd.erl](https://github.com/apache/couchdb/blob/main/src/nouveau/src/nouveau_httpd.erl)): Nouveau only accepts: `q`, `locale`, `partition`, `limit`, `top_n`, `sort`, `ranges`, `counts`, `update`, `bookmark`, `include_docs`. No `skip`.

**Tested against CHT 5.1.0:**
```bash
# POST skip=0, limit=3 → returns: 006834f0, a527fc92, 000686a3
# POST skip=3, limit=3 → returns: 006834f0, a527fc92, 000686a3  (SAME!)
# POST skip=100, limit=3 → returns: 006834f0, a527fc92, 000686a3 (SAME!)
# POST with bookmark from page 1 → returns: d3e66f49, 08c976e3  (CORRECT next page)
```

Nouveau only supports **bookmark-based pagination** ([cht-core nouveau.ts reference](https://github.com/medic/cht-core/blob/master/shared-libs/cht-datasource/src/local/libs/nouveau.ts#L59-L68)):
```js
body: JSON.stringify({
  bookmark: cursor,  // NOT skip
  limit,
  q: ...,
  sort: ...,
})
```

With `BATCH_SIZE=10000`, this is masked because most datasets fit in one page. But it will infinite-loop for >10K reports.

**Note:** This is pre-existing (the `skip` param was there before this PR), but since this PR is specifically about fixing pagination for large datasets, it should be addressed here.

**Suggested approach:** Change `getReportsByFreetext` to accept/return a `bookmark` instead of `skip`, and update the caller loop in `updateReports` accordingly.

File: src/lib/hierarchy-operations/hierarchy-data-source.js [hunk 6]
```diff
@@ -78,7 +78,7 @@ const fetchReportsByCreator = async (db, createdByIds, skip) => {
 
   const coreVersion = await getValidApiVersion();
   if (coreVersion && semver.gte(coreVersion, NOUVEAU_MIN_VERSION)) {
-    return await api().getReportsByCreatedByIds(createdByIds, BATCH_SIZE, skip);
+    return await api().getReportsByFreetext(createdByIds, BATCH_SIZE, skip);
```
Comment (sugat009) [inline src/lib/hierarchy-operations/hierarchy-data-source.js]: **issue (non-blocking):** `getValidApiVersion()` (line 79) calls `api().version()` which makes an HTTP GET to `/api/deploy-info` on every invocation (see `get-api-version.js:6-18`). Since `fetchReportsByCreator` is called inside a `do/while` loop in `index.js:updateReports`, this results in an extra HTTP round-trip per batch iteration.

Consider fetching the version once before the loop and passing it in, or caching the result.

File: test/lib/hierarchy-operations/hierarchy-operations.spec.js [hunk 7]
```diff
@@ -978,8 +978,7 @@ describe('hierarchy-operations', () => {
       );
     });
```
Comment (sugat009) [inline test/lib/hierarchy-operations/hierarchy-operations.spec.js:979]: **issue (non-blocking):** The previous tests that verified batching behavior (multiple view calls with incrementing `skip`) were removed, but no replacement pagination test was added.

It would be valuable to have at least one test that verifies the pagination loop terminates correctly and processes all reports across multiple batches — especially since the Nouveau path needs `bookmark`-based pagination while the CouchDB view path uses `skip`.

**Review by sugat009 — CHANGES_REQUESTED** [review]
Thanks for the updates Binod! The split into independent pagination loops is a solid improvement. I tested this against a live CHT 5.1.0 instance and found a critical issue with how Nouveau pagination works, plus a few other items.

**Testing setup:** Generated 21 contacts + 75 reports using test-data-generator, set `BATCH_SIZE=10` to force pagination, ran `move-contacts`. The command infinite-looped producing 50K+ log lines of repeated "already exists" warnings.

**Root cause:** Nouveau ignores the `skip` parameter entirely — it's not a supported parameter. See inline comments for details.

---

**nitpick (non-blocking):** Minor guard inconsistency in `fetchReportsBySubject` (hierarchy-data-source.js:89) — `fetchReportsByCreator` guards with `createdByIds.length === 0` while `fetchReportsBySubject` guards with `createdAtIds.length <= 0`. Since array length can't be negative, they're functionally equivalent, but using the same style in both would be cleaner.

**Sources:**
- [CouchDB Nouveau API docs](https://docs.couchdb.org/en/stable/api/ddoc/nouveau.html)
- [CouchDB Nouveau source (nouveau_httpd.erl)](https://github.com/apache/couchdb/blob/main/src/nouveau/src/nouveau_httpd.erl) — `skip` is not in the list of accepted parameters
- [cht-core nouveau.ts](https://github.com/medic/cht-core/blob/master/shared-libs/cht-datasource/src/local/libs/nouveau.ts) — uses `bookmark`, not `skip`

File: src/lib/hierarchy-operations/hierarchy-data-source.js (hunk 6 above)
Comment (binokaryg) [reply src/lib/hierarchy-operations/hierarchy-data-source.js]: Fixed. Extracted `useNouveauSearch()` which is called once in `updateReports` and the result is passed to `fetchReportsByCreator` on each iteration. Avoided module-level caching since it caused test leaks across suites.

File: test/lib/hierarchy-operations/hierarchy-operations.spec.js (hunk 7 above)
Comment (binokaryg) [reply test/lib/hierarchy-operations/hierarchy-operations.spec.js:979]: Added two tests: one verifying skip-based pagination for CHT 4.15.0 (view path) and one verifying bookmark-based pagination for CHT 5.0.0 (Nouveau path).

File: src/lib/api.js (hunk 5 above)
Comment (binokaryg) [reply src/lib/api.js]: This is getting out of hand :)

I have made changes. Nouveau path now uses bookmark-based pagination. Also added ID batching (100 per request) since large hierarchies (230K+ descendants) cause invalid_json / req_timedout errors when all IDs are sent in one query body. Outer loop checks `result.cursor && result.docs.length >= BATCH_SIZE` to stop correctly when Nouveau returns all results.

This time, I tested it successfully against a production replica instance moving 229K contacts and 461K reports which took about 3 hours to complete.

**Review by sugat009 — APPROVED** [review]

**Comment by binokaryg** [comment]
Thanks for the approval @sugat009.

I tested it successfully against a production replica instance (5.x) moving 229K contacts and 461K reports which took about 3 hours to complete.

Also tested successfully on a local 4.x instance moving 113K contacts, 13K reports (took about 11 minutes).
